name: mariaisabel
favicon: null
layout_spectrum: 0.4569080367218703
typography_spectrum: 0.04303183895535767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9527353991288692
  lightness: 0.7025747031439096
  saturation: 0.42657210142351687
  rhythmicContrast: 0.06014496507123113
purpose: []
